# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index

version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.66.0
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - *RESTORE_REGISTRY
      - run: rustc --version | tee ~/rust-version
      - run: cargo fmt -- --check
      - run: cargo test --all
      - *SAVE_REGISTRY
