[package]
name = "static-assets-hyper"
version = "0.1.0"
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
edition = "2018"

[dependencies]
anyhow = { version = "1.0.56", features = [ "backtrace" ] }
hyper = { version = "0.14.17", features=["tcp", "http1", "server"]}
tokio = { version = "1.17.0", features = ["rt"] }
static-assets = { version = "^0.1", path = "../core" }
static-assets-macros = { version = "^0.1", path = "../macros" }
futures = "0.3.21"
tower-http = "0.2.5"
tower = "0.4.12"
log = "0.4.14"

[dev-dependencies]
env_logger = "0.9.0"
tokio = {version="1.17.0", features=["full"]}
tower-http = { version = "0.2.5", features = [] }
tower = { version = "0.4.12", features=["util"] }
typed-headers = "0.2.0"
mime = "0.3.16"
